### ISSUE TITLE
Issue with docker container not having steam

### ISSUE THREAD

**Issue by LFAdams** [PassiveLemon/tmodloader1.4-docker#4]
Hello,
I am trying to get this docker container to work on my unraid server and having some issues.
my server.log shows the error 
[Main Thread/ERROR] [tML]: Steam Game Server failed to Init. Steam Workshop downloading on GoG is unavailable. Make sure Steam is installed
and I can see in the instructions.txt that i need to "install steamcmd to the server", but I am not too sure how I can do this in docker? All my other game servers that use steamcmd seem to have it packed in to the docker when it gets pulled. Can I just paste the steam files in like i did the mods? any help would be awesome. Id really like to get a 1.4 server up with mods! thanks.

**Comment by LFAdams** [comment]
I fixed the issue in my container and forked the repo and made some changes that automated the steamcmd installations in an attempts to make this more userfriendly and functional on UnRaid. Initial tests seem to be working well.
https://github.com/LFAdams/tmodloader1.4-docker

**Comment by PassiveLemon** [comment]
Mine runs fine without it. I believe that is just to be able to download and update mods but you shouldn't need that if you upload the modpack yourself which is in the instructions. That's why I have it install the server stuff to a directory of the hosts. I was planning on implementing Steam into it at some point though. 

Does not having Steam completely stop the container from running or cause any issues?

**Comment by PassiveLemon** [comment]
I'll work on it at some point but due to lack of response, I'll close this.
